version: "{build}"
clone_folder: "c:/WORK"

environment:
  global:
    CABOPTS: "--store-dir=c:/SR --http-transport=plain-http"
    C_INCLUDE_PATH: "c:/msys64/mingw64/include"
    LIBRARY_PATH: "c:/msys64/mingw64/lib;c:/msys64/mingw64/bin"
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    # 32-bit
    - GHCVER: "8.4.3"
      CHOCOPTS: --forcex86
    # 64-bit
    - GHCVER: "8.4.3"
      CHOCOPTS:

    - GHCVER: "8.2.2"
      CHOCOPTS:
    - GHCVER: "8.0.2"
      CHOCOPTS:
    - GHCVER: "7.10.3.2"
      CHOCOPTS:
    - GHCVER: "7.8.4.1"
      CHOCOPTS:
    - GHCVER: "7.6.3.1"
      CHOCOPTS:

cache:
 - "c:/SR"

install:
 - "choco install -y cabal %CHOCOPTS%"
 - "choco install -y ghc --version %GHCVER% %CHOCOPTS%"
 - "refreshenv"
 - "set PATH=C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;%PATH%;C:\\ghc\\ghc-%GHCVERSION%\\bin;C:\\hsbin"
 - "cabal --version"
 - "ghc --version"
 - "cabal %CABOPTS% update -vverbose+nowrap"
 - "cabal %CABOPTS% install -j1 alex --bindir=/hsbin"
 - "set RTSOPTS=--generate-crash-dump"
 - "cabal %CABOPTS% install -j1 -v3 happy --bindir=/hsbin"
 - "set RTSOPTS="
 - "alex --version"
 - "happy --version"

build: off

test_script:
 - "cabal install --only-dependencies --enable-tests"
 - "make sdist"
 - "cd dist"
 - "tar xvzf happy-*.tar.gz"
 - "cd happy-*/"
 - "cabal configure --enable-tests"
 - "cabal build"
 - "cabal test --show-details=direct"
